[package]
name = "rp-client"
version = "0.1.0"
authors = ["Valeriy Kostikov <mkoctuk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# http = "0.1"
failure = "0.1"

[dev-dependencies]
lazy_static = "1.4"